config/routes.rb
Nefarian::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  
  root :to => 'sessions#new'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/quest.rb
class Quest < ActiveRecord::Base
  
  belongs_to :user
  
  validates :user_id, :presence => true
  validates :quest_id, :presence => true
  
  default_scope :order => 'quests.created_at DESC'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessor :password
  attr_accessible :email, :name, :password, :password_confirmation
  
  has_many :quests, :dependent => :destroy
    
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, :presence => true, 
                    :format   => {:with => email_regex},
                    :uniqueness => {:case_sensitive => false}                 
                   
  validates :name, :presence => true,
                   :length => {:maximum => 20}
                  
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => {:within => 6..20}             
                      
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, salt)
    user = find_by_id(id)
    return nil if user.nil?
    return user if (user && user.salt==salt)
  end  
  
  private 
  
    def encrypt_password
      self.salt = secure_hash("#{Time.now.utc}--#{password}") if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(s)
      secure_hash("#{salt}--#{s}")
    end
    
    def secure_hash(s)
      Digest::SHA2.hexdigest(s)
    end   
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    user = current_user
    if user.nil?
      @title = "Sign in"
    else
      redirect_to user
    end
  end
  
  def create
    user = User.authenticate(params[:session][:email], 
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end
  
  def destroy
      sign_out
      redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @quests = @user.quests.paginate(:page => params[:page])
    @title = @user.name
  end
  
  def new
    @user = User.new
    @title = "Sign up"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end  
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end  
  
  private
  
    def user_from_remember_token
      User.authenticate_with_salt(*(cookies.signed[:remember_token] || [nil, nil]))
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  
end

app/views/layouts/_header.html.erb
<ul>
	<li><%= link_to "Home", root_path %></li>
	<% if signed_in? %>
		<li><%= link_to "Sign out", signout_path, :method => :delete %></li> 
	<% else %>
		<li><%= link_to "Sign in", signin_path %></li> 
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= @title %></title>
		<%= stylesheet_link_tag :all %>
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<%= yield %>
        <%= debug(params) if Rails.env.development? %>
	</body>
</html>

app/views/quests/_quest.html.erb
<tr>
	<td><%= quest.quest_id %></td>
	<td>Posted <%= time_ago_in_words(quest.created_at) %> ago.</td>
</tr>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div>
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<div>
		<%= f.label :email %></br>
		<%= f.text_field :email %>
	</div>
	<div>
		<%= f.label :name %></br>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :password %></br>
		<%= f.password_field :password %>
	</div>
	<div>
		<%= f.label :password_confirmation, "Confirmation" %></br>
		<%= f.password_field :password_confirmation %>
	</div>
  	<div class="actions">
    	<%= f.submit "Sign up" %>
  	</div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<% unless @user.quests.empty? %>
<table>
	<%= render @quests %>
</table>
<%= will_paginate @quests %>
<% end %>